cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:record_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:record_id>/', views.cart_remove, name='cart_remove'),
]

# url(r'^remove/(?P<record_id>\d+)/$', views.cart_remove, name='cart_remove'),

mainapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'mainapp'


urlpatterns = [
    path('', views.mainview, name="mainview"),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('search/', views.search, name="searchresults"),
    path('everythingsearch/', views.everythingsearch, name="everythingsearch"),
    path('albumsearch/', views.albumsearch, name="albumsearch"),
    path('artistsearch/', views.artistsearch, name="artistsearch"),
    path('recordlabelsearch/', views.recordlabelsearch, name="recordlabelsearch"),
    path('allfromlabel/', views.seeallfromlabel, name="allfromlabel"),
    path('allfromartist/', views.seeallfromartist, name="allfromartist"),




]

mainsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace="mainapp")),
    path('', include('cartapp.urls', namespace="cartapp")),


]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.urls import reverse


class Record(models.Model):
    recordid = models.CharField(max_length=100, default="recordid")
    artist = models.ForeignKey(
        'Artist', on_delete=models.PROTECT, null=True, blank=True)
    title = models.CharField(max_length=700, default="title")
    barcode = models.CharField(max_length=100, default="barcode")
    unit = models.CharField(max_length=100, default="unit")
    recordformat = models.CharField(max_length=100, default="recordformat")
    label = models.ForeignKey(
        'Label', on_delete=models.PROTECT, null=True, blank=True)
    price = models.CharField(max_length=100, default="price")
    precision = models.CharField(max_length=100, default="precision")
    delivery = models.CharField(max_length=100, default="delivery")
    stock = models.CharField(max_length=100, default="stock")
    date = models.CharField(max_length=100, default="date")

    wikiinfo = models.TextField(default="wikiinfo")
    wikilink = models.CharField(max_length=500, default="wikilink")
    discogspicurl = models.CharField(max_length=500, default="discogpicurl")
    ytlink = models.CharField(max_length=500, default="ytlink")
    coverimage = models.ImageField(
        blank=True, null=True, upload_to='coverimages/')
    slug = models.SlugField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('mainapp:product_detail', kwargs={'slug': self.slug})


class Label(models.Model):
    name = models.CharField(max_length=700, default="name")
    wikiinfo = models.TextField(default="wikiinfo")
    wikiinfolink = models.CharField(max_length=700, default="wikiinfolink")


class Artist(models.Model):
    name = models.CharField(max_length=700, default="name")
    wikiinfo = models.TextField(default="wikiinfo")
    wikiinfolink = models.CharField(max_length=700, default="wikiinfolink")

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Record, Artist, Label
from cartapp.forms import CartAddProductForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from urllib.parse import urlencode
from django.shortcuts import redirect


def mainview(request):

    allrecords = Record.objects.all()[0:10]

    return render(request, "mainapp/searchpage.html", {"allrecords": allrecords})


def product_detail(request, slug):
    record = get_object_or_404(Record, slug=slug)
    cart_product_form = CartAddProductForm()
    artist = record.artist
    products_from_artist = Record.objects.filter(
        artist=artist).exclude(slug=slug)
    products_from_artist1 = products_from_artist[0:3]
    label = record.label
    products_from_label = Record.objects.filter(label=label).exclude(slug=slug)
    products_from_label1 = products_from_label[0:3]
    request.session['artist'] = artist.name
    request.session['label'] = label.name

    context = {'record': record,
               'cart_product_form': cart_product_form, 'products_from_artist': products_from_artist, 'products_from_artist1': products_from_artist1, 'products_from_label': products_from_label, 'products_from_label1': products_from_label1
               }
    return render(request, 'mainapp/detail.html', context)


def search(request):

    query = request.GET.get('q')
    if "everything" in request.GET:
        base_url = reverse('mainapp:everythingsearch')
        query_string = urlencode({'query': query})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)

    elif "albumtitles" in request.GET:
        base_url = reverse('mainapp:albumsearch')
        query_string = urlencode({'query': query})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)

    if "artistnames" in request.GET:
        base_url = reverse('mainapp:artistsearch')
        query_string = urlencode({'query': query})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)

    if "recordlabels" in request.GET:
        base_url = reverse('mainapp:recordlabelsearch')
        query_string = urlencode({'query': query})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)


def everythingsearch(request):

    query = request.GET.get('query')
    qs = Record.objects.filter(Q(wikiinfo__icontains=query) | Q(
        label__wikiinfo__icontains=query) | Q(artist__wikiinfo__icontains=query))

    allresults = qs.order_by('pk')

    paginator = Paginator(allresults, 10)
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {'results': results, 'query': query}

    return render(request, 'mainapp/everythingsearch.html', context)


def albumsearch(request):

    query = request.GET.get('query')
    qs = Record.objects.filter(Q(title__icontains=query))

    allresults = qs.order_by('pk')

    paginator = Paginator(allresults, 10)
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {'results': results, 'query': query}

    return render(request, 'mainapp/albumsearch.html', context)


def artistsearch(request):

    query = request.GET.get('query')
    qs = Artist.objects.filter(Q(name__icontains=query))

    allresults = qs.order_by('pk')
    print(allresults)

    paginator = Paginator(allresults, 5)
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {'results': results, 'query': query}
    # print(context)

    return render(request, 'mainapp/artistsearch.html', context)


def recordlabelsearch(request):

    query = request.GET.get('query')
    qs = Label.objects.filter(Q(name__icontains=query))

    allresults = qs.order_by('pk')

    paginator = Paginator(allresults, 5)
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {'results': results, 'query': query}

    return render(request, 'mainapp/labelsearch.html', context)


def seeallfromartist(request):

    artist = request.session['artist']
    allfromartist = Record.objects.filter(artist=artist)

    return render(request, 'mainapp/seeall.html', {'allfromartist': queryset, 'title': artist})


def seeallfromlabel(request):

    label = request.session['label']
    allfromlabel = Record.objects.filter(label__name=label)

    return render(request, 'mainapp/seeall.html', {'queryset': allfromlabel, 'title': label})

mainapp/templates/mainapp/albumsearch.html
{% extends 'mainapp/base_search.html' %}

{% load static %}

{% block extrahead2 %}
<link rel="stylesheet" href="{% static "mainapp/css/searchstyles1.css" %}">
{% endblock %}



{% block search %}

<div class="titlequerydiv"> 
Showing results for {{query}}:

</div>

<div class="backgrounddiv"> 

{% for record in results %}

<div class="outsidediv">

<div class="upperdiv"> </div>

<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">

<a href="{{ record.get_absolute_url }}">
<img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
</a>

<div class="titlediv">
<div class="artistnamediv">
{{record.artist.name}}
</div>
<div class="recordtitlediv">
{{record.title}}
</div>
<div class="recordlabeldiv">
{{record.label.name}}
</div>
<div class="descriptionsdiv">
{{record.wikiinfo}}
<br>
{{record.artist.wikiinfo}}
<br>
{{record.label.wikiinfo}}
</div>

</div>

</div>
</div>






{% endfor %}  

</div>

{% endblock %}

mainapp/templates/mainapp/artistsearch.html
{% extends 'mainapp/base_search.html' %}

{% load static %}
{% load main_extras %}


{% block extrahead4 %}
<link rel="stylesheet" href="{% static "mainapp/css/searchstyles2.css" %}">
{% endblock %}



{% block search %}

<div>

<div class="titlequerydiv"> 
Showing results for {{query}}:

</div>



{% for artist in results %}
{% get_records_artist artist.name as records %}

<div>



<div class="generalartistdiv"> 

{{artist.name}}
<br>
{{artist.wikiinfo}}
<br>
{{artist.wikiinfolink}}
<br>
</div>






<div class="backgrounddiv" >




    {% for record in records %}
    <div>

    <div class="innerrecordsdiv">
 
    <img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">
     
    <a href="{{ record.get_absolute_url }}">
    <img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
    </a>

    <div class="titlediv">
    <div class="recordartist"> 
    {{record.artist.name}}
    </div>
    <div class="recordtitle">
    {{record.title}}


    </div>
    


    <div class="recordlabeletc">
    {{record.label.name}}
    <br>


   {{record.unit}}{{record.recordformat}}
    <br>
   {{record.price}}
    </div>

    </div>




    </div>

    </div>
    {% endfor %} 



</div>
</div> 
{% endfor %}   

</div>

{% if results.paginator.num_pages > 1 %}

    <div class="paginator">
        {% if results.has_previous %}
            <a href="?page=1&query={{query}}">First</a>
            <a href="?page={{ results.previous_page_number }}&query={{query}}">Previous</a>
        {% endif %}
        <span>{{ results.number }}</span><span>of</span> <span>{{ results.paginator.num_pages }}</span>
        {% if results.has_next %}
            <a href="?page={{ results.next_page_number }}&query={{query}}">Next</a>
            <a href="?page={{ results.paginator.num_pages }}&query={{query}}">Last</a>
        {% endif %}
    </div>

{% endif %}  








{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/basestyles.css'%}"/>
<link href="https://fonts.googleapis.com/css?family=Comfortaa|Source+Code+Pro:400,600,700&display=swap" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% block extrahead %}{% endblock %}
{% block extrahead2 %}{% endblock %}
{% block extrahead3 %}{% endblock %}
{% block extrahead4 %}{% endblock %}
{% block extrahead5 %}{% endblock %}

</head>
<body>

<header class="header"> 

<div>
<img class="textlogo" src="{% static 'mainapp/images/textlogo.png' %}">
</div>
<div>
<a href="{% url "cartapp:cart_detail" %}">
<img class="cart" src="{% static 'mainapp/images/whitecart.png' %}">
</a>
</div>
<div>
<a href="{% url "mainapp:mainview" %}">
<img class="search" src="{% static 'mainapp/images/whitesearchicon.png' %}">
</a>

</div>




<div class="contextprocessordiv">
{% with total_items=cart|length %}
    {% if cart|length > 0 %}
           ({{ total_items }})
        
    {% else %}
       (O)
    {% endif %}
{% endwith %} 

</div>



</header>






{% block content %}
{% endblock %}

{% block search %}
{% endblock %}

{% block detail %}
{% endblock %}

{% block cart %}
{% endblock %}

{% block seeall %}
{% endblock %}












<div class="footer">
<div>

<img class="bottomlogo" src="{% static 'mainapp/images/logo.png' %}">
</div>
</div>


</body>

</body>
</html>

mainapp/templates/mainapp/base_search.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static "mainapp/css/basesearchstyles.css" %}">
{% endblock %}





{% block content %}




<div class="searchdiv"> 


<form action="{% url 'mainapp:searchresults' %}" method="GET" >


<input type="text" name="q" action="/search/" class="input" placeholder="Search...">  </input>
<div class="everythingdiv">
<input id="mtka" value="everything" type="submit" name="everything" class="btn1"></input>
</div>
<div class="titlesdiv">
<input value="album titles" type="submit" name="albumtitles"  class="btn2"</input>
</div>
<div class="artistdiv">
<input value="artist names" type="submit" name="artistnames" class="btn3"> </input>
</div>
<div class="labeldiv">
<input value="record labels" type="submit" name="recordlabels" class="btn4"> </input>
</div>
</form>




</div>





{% endblock %}


{% block search %}
{% endblock %}

{% block titlesearch %}
{% endblock %}

mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}

{% load static %}


{% block extrahead3 %}
<link rel="stylesheet" href="{% static "mainapp/css/detailstyles.css" %}">
{% endblock %}

{% block detail %}


<div class="contentdiv">

<img class="vinylrecord" src="{% static 'mainapp/images/vinylrewhite.png'%}">
<img class="vinylcover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">


<div class="maintitlediv">

<div class="mainrecordtitle"> 
{{record.artist.name}}
<br>
{{record.title}}
</div>
<br>

{{record.label.name}}

</div>
</div>



<div class="moreinfodiv"> 

<form action="{% url "cart:cart_add" record.id %}" method="POST">
{% csrf_token %}
<div class="addtocart">
<input type="submit" value="add to cart" class="btnadd" data-add="{% url "cart:cart_add" record.id %}" data-remove="{% url "cart:cart_remove" record.id %}" > </input>
</div>
</form>
<script>
$(document).ready(function(){
$('.btnadd').click(function() {


   if  ($('.btnadd').val() == 'add to cart') {
    $('.btnadd').val('remove from cart'); 
    {% comment %} $('.btnadd').attr("data-remove"); {% endcomment %}


   }
   
   else {
       $('.btnadd').val('add to cart'); 
       {% comment %} $('.btnadd').attr("data-add"); {% endcomment %}
   
   } 



});
});

{% comment %} function add_to_cart() {
    $('.btnadd').val('remove from cart');

}

function remove_from_cart() {
    $('.btnadd').val('add to cart');

}  {% endcomment %}





</script>



<div class="basicinfodiv"> 
<div class="basicinfotitle">
Item details:
</div>
<br>


<br>
Barcode: {{record.barcode}}
<br>
ID number: {{record.recordid}}
<br>
{{record.unit}}{{record.recordformat}}
<br>
{{record.price}}
</div>

<div class="detailinfodiv">
<div class="detailinfotitle">
Tracklist:
</div>
<br>


A1	Song	
<br>
A2	Placeholder	
<br>
A3	Foo
<br>
A4	Bar
<br>
B1	Song	
<br>
B2	Lorem
<br>	
B3	Ipsum	
<br>
B4	Song
<br>
B5	Placeholder

</div>
</div>






<div class="videodiv"> 
<iframe class="frame" src="https://www.youtube.com/embed/NY6hBKdCaV4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


</div>

<div class="descriptiondiv"> 
<div class="detaildescription">
<div class="detailtitle"> More info: </div>

<br>

{{record.wikiinfo}}

{{record.wikilink}}

<br>



<br>











</div>
</div>

{% if products_from_artist1.count > 0 %}

<div class="morefromartisttitle">
More from artist:


</div>



<div class="morefromartistdiv"> 


{% for record in products_from_artist1 %}

<div>

<div class="innerrecordsdiv">

<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">
     
    <a href="{{ record.get_absolute_url }}">
    <img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
    </a>

    <div class="titlediv">
    <div class="recordartist"> 
    {{record.artist.name}}
    </div>
    <div class="recordtitle">
    {{record.title}}


    </div>
    


    <div class="recordlabeletc">
    {{record.label.name}}
    <br>


   {{record.unit}}{{record.recordformat}}
    <br>
   {{record.price}}
    </div>

    </div>




    </div>

    </div>



{% endfor %} 

{% if products_from_artist.count > products_from_artist1.count %} 


<a href="{% url "mainapp:allfromartist" %}">
<div class="seemore">
see all
</div>
</a>

</div>

{% endif %}

{% endif %}


</div>

{% if products_from_label1.count > 0 %} 

<div class="morefromlabeltitle">
More from label:


</div>

<div class="morefromlabeldiv"> 

{% for record in products_from_label1 %}

<div>

<div class="innerrecordsdiv">

<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">
     
<a href="{{ record.get_absolute_url }}">
<img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
</a>

<div class="titlediv">
<div class="recordartist"> 
{{record.artist.name}}
</div>
<div class="recordtitle1">
{{record.title}}


</div>



<div class="recordlabeletc">
{{record.label.name}}
<br>


{{record.unit}}{{record.recordformat}}
<br>
{{record.price}}
</div>

</div>




</div>





</div>



{% endfor %} 

{% if products_from_label.count > products_from_label1.count %} 


<a href="{% url "mainapp:allfromlabel" %}">
<div class="seemore">
see all
</div>
</a>

</div>

{% endif %}

{% endif %}















{% endblock %}

mainapp/templates/mainapp/everythingsearch.html
{% extends 'mainapp/base_search.html' %}

{% load static %}

{% block extrahead2 %}
<link rel="stylesheet" href="{% static "mainapp/css/searchstyles1.css" %}">
{% endblock %}



{% block search %}

<div class="titlequerydiv"> 
Showing results for {{query}}:

</div>



<div class="backgrounddiv"> 

{% for record in results %}

<div class="outsidediv">

<div class="upperdiv"> </div>

<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">

<a href="{{ record.get_absolute_url }}">
<img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
</a>

<div class="titlediv">
<div class="artistnamediv">
{{record.artist.name}}
</div>
<div class="recordtitlediv">
{{record.title}}
</div>
<div class="recordlabeldiv">
{{record.label.name}}
</div>
<div class="descriptionsdiv">
{{record.wikiinfo}}
<br>
{{record.artist.wikiinfo}}
<br>
{{record.label.wikiinfo}}
</div>
</div>


</div>
</div>






{% endfor %}  

</div>


{% if results.paginator.num_pages > 1 %}

    <div class="paginator">
        {% if results.has_previous %}
            <a href="?page=1&query={{query}}">First</a>
            <a href="?page={{ results.previous_page_number }}&query={{query}}">Previous</a>
        {% endif %}
        <span>{{ results.number }}</span><span>of</span> <span>{{ results.paginator.num_pages }}</span>
        {% if results.has_next %}
            <a href="?page={{ results.next_page_number }}&query={{query}}">Next</a>
            <a href="?page={{ results.paginator.num_pages }}&query={{query}}">Last</a>
        {% endif %}
    </div>

{% endif %}    






{% endblock %}

mainapp/templates/mainapp/labelsearch.html
{% extends 'mainapp/base_search.html' %}

{% load static %}
{% load main_extras %}


{% block extrahead4 %}
<link rel="stylesheet" href="{% static "mainapp/css/searchstyles2.css" %}">
{% endblock %}



{% block search %}

<div>

<div class="titlequerydiv"> 
Showing results for {{query}}:

</div>



{% for artist in results %}
{% get_records_label artist.name as records %}

<div>



<div class="generalartistdiv"> 

{{artist.name}}
<br>
{{artist.wikiinfo}}
<br>
{{artist.wikiinfolink}}
<br>
</div>






<div class="backgrounddiv" >




    {% for record in records %}
    <div>

    <div class="innerrecordsdiv">
 
    <img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">
     
    <a href="{{ record.get_absolute_url }}">
    <img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
    </a>

    <div class="titlediv">
    <div class="recordartist"> 
    {{record.artist.name}}
    </div>
    <div class="recordtitle">
    {{record.title}}


    </div>
    


    <div class="recordlabeletc">
    {{record.label.name}}
    <br>


   {{record.unit}}{{record.recordformat}}
    <br>
   {{record.price}}
    </div>

    </div>




    </div>

    </div>
    {% endfor %} 



</div>
</div> 
{% endfor %}   

</div>

{% if results.paginator.num_pages > 1 %}

    <div class="paginator">
        {% if results.has_previous %}
            <a href="?page=1&query={{query}}">First</a>
            <a href="?page={{ results.previous_page_number }}&query={{query}}">Previous</a>
        {% endif %}
        <span>{{ results.number }}</span><span>of</span> <span>{{ results.paginator.num_pages }}</span>
        {% if results.has_next %}
            <a href="?page={{ results.next_page_number }}&query={{query}}">Next</a>
            <a href="?page={{ results.paginator.num_pages }}&query={{query}}">Last</a>
        {% endif %}
    </div>

{% endif %}  








{% endblock %}

mainapp/templates/mainapp/searchpage.html
{% extends 'mainapp/base_search.html' %}

{% load static %}

{% block extrahead2 %}
<link rel="stylesheet" href="{% static "mainapp/css/searchstyles1.css" %}">
{% endblock %}



{% block search %}


<div class="backgrounddiv"> 


{% for record in allrecords %}

<div class="outsidediv">

<div class="upperdiv"> </div>


<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">


<a href="{{ record.get_absolute_url }}">
<img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
</a>

<div class="titlediv">
<div class="artistnamediv">
{{record.artist.name}}
</div>
<div class="recordtitlediv">
{{record.title}}
</div>
<div class="recordlabeldiv">
{{record.label.name}}
</div>
<div class="descriptionsdiv">
{{record.wikiinfo}}
<br>
{{record.artist.wikiinfo}}
<br>
{{record.label.wikiinfo}}
</div>






</div>

</div>




{% endfor %}  

</div>

{% endblock %}

mainapp/templates/mainapp/seeall.html
{% extends 'mainapp/base.html' %}

{% load static %}


{% block extrahead3 %}
<link rel="stylesheet" href="{% static "mainapp/css/detailstyles.css" %}">
{% endblock %}

{% block seeall %}


<div class="seemorebackground">

<div class="seemoretitle">
All records from {{title}}:

</div>

{% for record in queryset %}

<div>

<div class="innerrecordsdiv">

<img class="vinyl" src="{% static 'mainapp/images/vinylrewhite.png'%}">
     
<a href="{{ record.get_absolute_url }}">
<img class="cover" src="{% if record.coverimage %} {{ record.coverimage.url }} {% else %} {% static 'mainapp/images/default.jpg' %} {% endif %}">
</a>

<div class="titlediv">
<div class="recordartist"> 
{{record.artist.name}}
</div>
<div class="recordtitle1">
{{record.title}}


</div>



<div class="recordlabeletc">
{{record.label.name}}
<br>


{{record.unit}}{{record.recordformat}}
<br>
{{record.price}}
</div>

</div>




</div>





</div>






{% endfor %}

</div>


{% endblock %}